name: genbook-dev

services:
  db:
    container_name: postgres-dev
    image: postgres:15
    environment:
      POSTGRES_DB: gen_book_dev
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    profiles: ["dev"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev_user -d gen_book_dev"]
      interval: 30s
      timeout: 10s
      retries: 3

  ai-book:
    container_name: ai-system-dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./assets:/app/assets:ro
    env_file:
      - .env.dev
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=development
      - DEBUG=True
    depends_on:
      db:
        condition: service_healthy
    profiles: ["dev"]
    restart: unless-stopped
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_dev_data:
