name: genbook-prod

services:
  db:
    container_name: postgres-prod
    image: postgres:15
    environment:
      POSTGRES_DB: gen_book_prod
      POSTGRES_USER: prod_user
      POSTGRES_PASSWORD: change_this_strong_password
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
    networks:
      - genbook-network
    profiles: ["prod"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U prod_user -d gen_book_prod"]
      interval: 30s
      timeout: 10s
      retries: 3

  ai-book:
    container_name: ai-system-prod
    image: genbook-api:latest
    env_file:
      - .env.prod
    environment:
      - ENVIRONMENT=production
      - DEBUG=False
    networks:
      - genbook-network
    profiles: ["prod"]
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    container_name: nginx-prod
    image: nginx:alpine
    ports:
      - "8007:80"
      - "8443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/ssl/certs:ro
    networks:
      - genbook-network
    profiles: ["prod"]
    depends_on:
      - ai-book
    restart: unless-stopped

volumes:
  postgres_prod_data:

networks:
  genbook-network:
    driver: bridge
