name: genbook-BE

services:
  db:
    container_name: postgres
    image: postgres:15
    environment:
      POSTGRES_DB: gen_book_db
      POSTGRES_USER: genbook_user
      POSTGRES_PASSWORD: genbook_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U genbook_user -d gen_book_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  ai-book:
    container_name: ai-system-api
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./assets:/app/assets:ro
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql://genbook_user:genbook_password@db:5432/gen_book_db
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_data:
